layout_spectrum: 0.6874262276105583
typography_spectrum: 0.5233378265984356
color:
  brandStrength: 0.8414358159061521
  lightness: 0.13884205115027726
  saturation: 0.5116734725888819
  rhythmicContrast: 0.5019219524692744
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Tick Talking
author:
  name: Anthony Lazzaro
  email: anthonylazzaro@gmail.com
  url: anthonylazzaro.com
